netbox/dcim/urls.py
from django.urls import path

from extras.views import ObjectChangeLogView, ImageAttachmentEditView
from ipam.views import ServiceCreateView
from . import views
from .models import (
    Cable, ConsolePort, ConsoleServerPort, Device, DeviceRole, DeviceType, FrontPort, Interface, Manufacturer, Platform,
    PowerFeed, PowerPanel, PowerPort, PowerOutlet, Rack, RackGroup, RackReservation, RackRole, RearPort, Region, Site,
    VirtualChassis,
)

app_name = 'dcim'
urlpatterns = [

    # Regions
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('regions/add/', views.RegionCreateView.as_view(), name='region_add'),
    path('regions/import/', views.RegionBulkImportView.as_view(), name='region_import'),
    path('regions/delete/', views.RegionBulkDeleteView.as_view(), name='region_bulk_delete'),
    path('regions/<int:pk>/edit/', views.RegionEditView.as_view(), name='region_edit'),
    path('regions/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='region_changelog', kwargs={'model': Region}),

    # Sites
    path('sites/', views.SiteListView.as_view(), name='site_list'),
    path('sites/add/', views.SiteCreateView.as_view(), name='site_add'),
    path('sites/import/', views.SiteBulkImportView.as_view(), name='site_import'),
    path('sites/edit/', views.SiteBulkEditView.as_view(), name='site_bulk_edit'),
    path('sites/delete/', views.SiteBulkDeleteView.as_view(), name='site_bulk_delete'),
    path('sites/<slug:slug>/', views.SiteView.as_view(), name='site'),
    path('sites/<slug:slug>/edit/', views.SiteEditView.as_view(), name='site_edit'),
    path('sites/<slug:slug>/delete/', views.SiteDeleteView.as_view(), name='site_delete'),
    path('sites/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='site_changelog', kwargs={'model': Site}),
    path('sites/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='site_add_image', kwargs={'model': Site}),

    # Rack groups
    path('rack-groups/', views.RackGroupListView.as_view(), name='rackgroup_list'),
    path('rack-groups/add/', views.RackGroupCreateView.as_view(), name='rackgroup_add'),
    path('rack-groups/import/', views.RackGroupBulkImportView.as_view(), name='rackgroup_import'),
    path('rack-groups/delete/', views.RackGroupBulkDeleteView.as_view(), name='rackgroup_bulk_delete'),
    path('rack-groups/<int:pk>/edit/', views.RackGroupEditView.as_view(), name='rackgroup_edit'),
    path('rack-groups/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackgroup_changelog', kwargs={'model': RackGroup}),

    # Rack roles
    path('rack-roles/', views.RackRoleListView.as_view(), name='rackrole_list'),
    path('rack-roles/add/', views.RackRoleCreateView.as_view(), name='rackrole_add'),
    path('rack-roles/import/', views.RackRoleBulkImportView.as_view(), name='rackrole_import'),
    path('rack-roles/delete/', views.RackRoleBulkDeleteView.as_view(), name='rackrole_bulk_delete'),
    path('rack-roles/<int:pk>/edit/', views.RackRoleEditView.as_view(), name='rackrole_edit'),
    path('rack-roles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackrole_changelog', kwargs={'model': RackRole}),

    # Rack reservations
    path('rack-reservations/', views.RackReservationListView.as_view(), name='rackreservation_list'),
    path('rack-reservations/add/', views.RackReservationCreateView.as_view(), name='rackreservation_add'),
    path('rack-reservations/import/', views.RackReservationImportView.as_view(), name='rackreservation_import'),
    path('rack-reservations/edit/', views.RackReservationBulkEditView.as_view(), name='rackreservation_bulk_edit'),
    path('rack-reservations/delete/', views.RackReservationBulkDeleteView.as_view(), name='rackreservation_bulk_delete'),
    path('rack-reservations/<int:pk>/', views.RackReservationView.as_view(), name='rackreservation'),
    path('rack-reservations/<int:pk>/edit/', views.RackReservationEditView.as_view(), name='rackreservation_edit'),
    path('rack-reservations/<int:pk>/delete/', views.RackReservationDeleteView.as_view(), name='rackreservation_delete'),
    path('rack-reservations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackreservation_changelog', kwargs={'model': RackReservation}),

    # Racks
    path('racks/', views.RackListView.as_view(), name='rack_list'),
    path('rack-elevations/', views.RackElevationListView.as_view(), name='rack_elevation_list'),
    path('racks/add/', views.RackCreateView.as_view(), name='rack_add'),
    path('racks/import/', views.RackBulkImportView.as_view(), name='rack_import'),
    path('racks/edit/', views.RackBulkEditView.as_view(), name='rack_bulk_edit'),
    path('racks/delete/', views.RackBulkDeleteView.as_view(), name='rack_bulk_delete'),
    path('racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path('racks/<int:pk>/edit/', views.RackEditView.as_view(), name='rack_edit'),
    path('racks/<int:pk>/delete/', views.RackDeleteView.as_view(), name='rack_delete'),
    path('racks/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rack_changelog', kwargs={'model': Rack}),
    path('racks/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='rack_add_image', kwargs={'model': Rack}),

    # Manufacturers
    path('manufacturers/', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    path('manufacturers/add/', views.ManufacturerCreateView.as_view(), name='manufacturer_add'),
    path('manufacturers/import/', views.ManufacturerBulkImportView.as_view(), name='manufacturer_import'),
    path('manufacturers/delete/', views.ManufacturerBulkDeleteView.as_view(), name='manufacturer_bulk_delete'),
    path('manufacturers/<slug:slug>/edit/', views.ManufacturerEditView.as_view(), name='manufacturer_edit'),
    path('manufacturers/<slug:slug>/changelog/', ObjectChangeLogView.as_view(), name='manufacturer_changelog', kwargs={'model': Manufacturer}),

    # Device types
    path('device-types/', views.DeviceTypeListView.as_view(), name='devicetype_list'),
    path('device-types/add/', views.DeviceTypeCreateView.as_view(), name='devicetype_add'),
    path('device-types/import/', views.DeviceTypeImportView.as_view(), name='devicetype_import'),
    path('device-types/edit/', views.DeviceTypeBulkEditView.as_view(), name='devicetype_bulk_edit'),
    path('device-types/delete/', views.DeviceTypeBulkDeleteView.as_view(), name='devicetype_bulk_delete'),
    path('device-types/<int:pk>/', views.DeviceTypeView.as_view(), name='devicetype'),
    path('device-types/<int:pk>/edit/', views.DeviceTypeEditView.as_view(), name='devicetype_edit'),
    path('device-types/<int:pk>/delete/', views.DeviceTypeDeleteView.as_view(), name='devicetype_delete'),
    path('device-types/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='devicetype_changelog', kwargs={'model': DeviceType}),

    # Console port templates
    path('console-port-templates/add/', views.ConsolePortTemplateCreateView.as_view(), name='consoleporttemplate_add'),
    path('console-port-templates/edit/', views.ConsolePortTemplateBulkEditView.as_view(), name='consoleporttemplate_bulk_edit'),
    path('console-port-templates/delete/', views.ConsolePortTemplateBulkDeleteView.as_view(), name='consoleporttemplate_bulk_delete'),
    path('console-port-templates/<int:pk>/edit/', views.ConsolePortTemplateEditView.as_view(), name='consoleporttemplate_edit'),
    path('console-port-templates/<int:pk>/delete/', views.ConsolePortTemplateDeleteView.as_view(), name='consoleporttemplate_delete'),

    # Console server port templates
    path('console-server-port-templates/add/', views.ConsoleServerPortTemplateCreateView.as_view(), name='consoleserverporttemplate_add'),
    path('console-server-port-templates/edit/', views.ConsoleServerPortTemplateBulkEditView.as_view(), name='consoleserverporttemplate_bulk_edit'),
    path('console-server-port-templates/delete/', views.ConsoleServerPortTemplateBulkDeleteView.as_view(), name='consoleserverporttemplate_bulk_delete'),
    path('console-server-port-templates/<int:pk>/edit/', views.ConsoleServerPortTemplateEditView.as_view(), name='consoleserverporttemplate_edit'),
    path('console-server-port-templates/<int:pk>/delete/', views.ConsoleServerPortTemplateDeleteView.as_view(), name='consoleserverporttemplate_delete'),

    # Power port templates
    path('power-port-templates/add/', views.PowerPortTemplateCreateView.as_view(), name='powerporttemplate_add'),
    path('power-port-templates/edit/', views.PowerPortTemplateBulkEditView.as_view(), name='powerporttemplate_bulk_edit'),
    path('power-port-templates/delete/', views.PowerPortTemplateBulkDeleteView.as_view(), name='powerporttemplate_bulk_delete'),
    path('power-port-templates/<int:pk>/edit/', views.PowerPortTemplateEditView.as_view(), name='powerporttemplate_edit'),
    path('power-port-templates/<int:pk>/delete/', views.PowerPortTemplateDeleteView.as_view(), name='powerporttemplate_delete'),

    # Power outlet templates
    path('power-outlet-templates/add/', views.PowerOutletTemplateCreateView.as_view(), name='poweroutlettemplate_add'),
    path('power-outlet-templates/edit/', views.PowerOutletTemplateBulkEditView.as_view(), name='poweroutlettemplate_bulk_edit'),
    path('power-outlet-templates/delete/', views.PowerOutletTemplateBulkDeleteView.as_view(), name='poweroutlettemplate_bulk_delete'),
    path('power-outlet-templates/<int:pk>/edit/', views.PowerOutletTemplateEditView.as_view(), name='poweroutlettemplate_edit'),
    path('power-outlet-templates/<int:pk>/delete/', views.PowerOutletTemplateDeleteView.as_view(), name='poweroutlettemplate_delete'),

    # Interface templates
    path('interface-templates/add/', views.InterfaceTemplateCreateView.as_view(), name='interfacetemplate_add'),
    path('interface-templates/edit/', views.InterfaceTemplateBulkEditView.as_view(), name='interfacetemplate_bulk_edit'),

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path, reverse
from django.views.generic.base import RedirectView
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
from netbox.views import APIRootView, HomeView, StaticMediaFailureView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site


# TODO: Remove in v2.9
class RQRedirectView(RedirectView):
    """
    Temporary 301 redirect from the old URL to the new one.
    """
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        return reverse('rq_home')


openapi_info = openapi.Info(
    title="NetBox API",
    default_version='v2',
    description="API to access NetBox",
    terms_of_service="https://github.com/netbox-community/netbox",
    license=openapi.License(name="Apache v2 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
)

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('secrets/', include('secrets.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('user/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/secrets/', include('secrets.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger'), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc'), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(), name='schema_swagger'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Admin
    path('admin/', admin_site.urls),
    path('admin/background-tasks/', include('django_rq.urls')),
    # TODO: Remove in v2.9
    path('admin/webhook-backend-status/', RQRedirectView.as_view()),

    # Errors
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),
    path('admin/plugins/', include(plugin_admin_patterns))
]


if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

if settings.METRICS_ENABLED:
    _patterns += [
        path('', include('django_prometheus.urls')),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

handler500 = 'utilities.views.server_error'

netbox/users/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('api-tokens/', views.TokenListView.as_view(), name='token_list'),
    path('api-tokens/add/', views.TokenEditView.as_view(), name='token_add'),
    path('api-tokens/<int:pk>/edit/', views.TokenEditView.as_view(), name='token_edit'),
    path('api-tokens/<int:pk>/delete/', views.TokenDeleteView.as_view(), name='token_delete'),
    path('user-key/', views.UserKeyView.as_view(), name='userkey'),
    path('user-key/edit/', views.UserKeyEditView.as_view(), name='userkey_edit'),
    path('session-key/delete/', views.SessionKeyDeleteView.as_view(), name='sessionkey_delete'),

]

netbox/users/models.py
import binascii
import os

from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone


__all__ = (
    'Token',
)


class Token(models.Model):
    """
    An API token used for user authentication. This extends the stock model to allow each user to have multiple tokens.
    It also supports setting an expiration time and toggling write ability.
    """
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='tokens'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    expires = models.DateTimeField(
        blank=True,
        null=True
    )
    key = models.CharField(
        max_length=40,
        unique=True,
        validators=[MinLengthValidator(40)]
    )
    write_enabled = models.BooleanField(
        default=True,
        help_text='Permit create/update/delete operations using this key'
    )
    description = models.CharField(
        max_length=200,
        blank=True
    )

    class Meta:
        pass

    def __str__(self):
        # Only display the last 24 bits of the token to avoid accidental exposure.
        return "{} ({})".format(self.key[-6:], self.user)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)

    def generate_key(self):
        # Generate a random 160-bit key expressed in hexadecimal.
        return binascii.hexlify(os.urandom(20)).decode()

    @property
    def is_expired(self):
        if self.expires is None or timezone.now() < self.expires:
            return False
        return True

netbox/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm as DjangoPasswordChangeForm

from utilities.forms import BootstrapMixin, DateTimePicker
from .models import Token


class LoginForm(BootstrapMixin, AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = ''
        self.fields['password'].widget.attrs['placeholder'] = ''


class PasswordChangeForm(BootstrapMixin, DjangoPasswordChangeForm):
    pass


class TokenForm(BootstrapMixin, forms.ModelForm):
    key = forms.CharField(
        required=False,
        help_text="If no key is provided, one will be generated automatically."
    )

    class Meta:
        model = Token
        fields = [
            'key', 'write_enabled', 'expires', 'description',
        ]
        widgets = {
            'expires': DateTimePicker(),
        }

netbox/templates/users/_user.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 col-md-2 col-md-offset-2">
        <ul class="nav nav-pills nav-stacked">
            <li{% ifequal active_tab "profile" %} class="active"{% endifequal %}>
                <a href="{% url 'user:profile' %}">Profile</a>
            </li>
            {% if not request.user.ldap_username %}
                <li{% ifequal active_tab "change_password" %} class="active"{% endifequal %}>
                    <a href="{% url 'user:change_password' %}">Change Password</a>
                </li>
            {% endif %}
            <li{% ifequal active_tab "api_tokens" %} class="active"{% endifequal %}>
                <a href="{% url 'user:token_list' %}">API Tokens</a>
            </li>
            <li{% ifequal active_tab "userkey" %} class="active"{% endifequal %}>
                <a href="{% url 'user:userkey' %}">User Key</a>
            </li>
        </ul>
    </div>
	<div class="col-sm-9 col-md-6">
        {% block usercontent %}{% endblock %}
	</div>
</div>
{% endblock %}

netbox/templates/users/api_tokens.html
{% extends 'users/_user.html' %}
{% load helpers %}

{% block title %}API Tokens{% endblock %}

{% block usercontent %}
    <div class="row">
        <div class="col-md-12">
            {% for token in tokens %}
                <div class="panel panel-{% if token.is_expired %}danger{% else %}default{% endif %}">
                    <div class="panel-heading">
                        <div class="pull-right noprint">
                            <a class="btn btn-xs btn-success copy-token" data-clipboard-target="#token_{{ token.pk }}">Copy</a>
                            {% if perms.users.change_token %}
                                <a href="{% url 'user:token_edit' pk=token.pk %}" class="btn btn-xs btn-warning">Edit</a>
                            {% endif %}
                            {% if perms.users.delete_token %}
                                <a href="{% url 'user:token_delete' pk=token.pk %}" class="btn btn-xs btn-danger">Delete</a>
                            {% endif %}
                        </div>
                        <i class="fa fa-key"></i>
                        <span id="token_{{ token.pk }}">{{ token.key }}</span>
                        {% if token.is_expired %}
                            <span class="label label-danger">Expired</span>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <span title="{{ token.created }}">{{ token.created|date }}</span><br />
                                <small class="text-muted">Created</small>
                            </div>
                            <div class="col-md-4">
                                {% if token.expires %}
                                    <span title="{{ token.expires }}">{{ token.expires|date }}</span><br />
                                {% else %}
                                    <span>Never</span><br />
                                {% endif %}
                                <small class="text-muted">Expires</small>
                            </div>
                            <div class="col-md-4">
                                {% if token.write_enabled %}
                                    <span class="label label-success">Enabled</span>
                                {% else %}
                                    <span class="label label-danger">Disabled</span>
                                {% endif %}<br />
                                <small class="text-muted">Create/edit/delete operations</small>
                            </div>
                        </div>
                        {% if token.description %}
                            <br /><span>{{ token.description }}</span>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p>You do not have any API tokens.</p>
            {% endfor %}
            {% if perms.users.add_token %}
                <a href="{% url 'user:token_add' %}" class="btn btn-primary">
                    <span class="fa fa-plus" aria-hidden="true"></span>
                    Add a token
                </a>
            {% else %}
                <div class="alert alert-info text-center" role="alert">
                    You do not have permission to create new API tokens. If needed, ask an administrator to enable token creation for your account or an assigned group.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
new ClipboardJS('.copy-token');
</script>
{% endblock %}

netbox/templates/users/change_password.html
{% extends 'users/_user.html' %}
{% load form_helpers %}

{% block title %}Change Password{% endblock %}

{% block usercontent %}
    <form action="." method="post" class="form form-horizontal">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="panel panel-danger">
                <div class="panel-heading"><strong>Errors</strong></div>
                <div class="panel-body">
                    {{ form.non_field_errors }}
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Password</strong></div>
            <div class="panel-body">
                {% render_field form.old_password %}
                {% render_field form.new_password1 %}
                {% render_field form.new_password2 %}
            </div>
        </div>
        <div class="text-right">
            <button type="submit" name="_update" class="btn btn-primary">Update</button>
            <a href="{% url 'user:profile' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
{% endblock %}

netbox/templates/users/profile.html
{% extends 'users/_user.html' %}
{% load helpers %}

{% block title %}User Profile{% endblock %}

{% block usercontent %}
    <small class="text-muted">User login</small>
    <h5>{{ request.user.username }}</h5>
    <small class="text-muted">Full name</small>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <small class="text-muted">Email</small>
    <h5>{{ request.user.email }}</h5>
    <small class="text-muted">Registered</small>
    <h5>{{ request.user.date_joined }}</h5>
    <small class="text-muted">Groups</small>
    <h5>{{ request.user.groups.all|join:', ' }}</h5>
    <small class="text-muted">Admin access</small>
    <h5>{{ request.user.is_staff|yesno|capfirst }}</h5>
{% endblock %}

netbox/templates/users/sessionkey_delete.html
{% extends 'utilities/obj_delete.html' %}

{% block message %}
    <p>Are you sure you want to delete your session key?</p>
{% endblock %}

netbox/templates/users/userkey.html
{% extends 'users/_user.html' %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if userkey %}
        <div class="pull-right noprint">
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-warning">
                <span class="fa fa-pencil" aria-hidden="true"></span>
                Edit user key
            </a>
        </div>
        <h4>
            Your user key is:
            {% if userkey.is_active %}
                <span class="label label-success">Active</span>
            {% else %}
                <span class="label label-danger">Inactive</span>
            {% endif %}
        </h4>
        {% include 'inc/created_updated.html' with obj=userkey %}
        {% if not userkey.is_active %}
            <div class="alert alert-warning" role="alert">
                <i class="fa fa-warning"></i>
                Your user key is inactive. Ask an administrator to enable it for you.
            </div>
        {% endif %}
        <pre>{{ userkey.public_key }}</pre>
        <hr />
        {% if userkey.session_key %}
            <div class="pull-right noprint">
                <a href="{% url 'user:sessionkey_delete' %}" class="btn btn-danger">
                    <span class="fa fa-trash" aria-hidden="true"></span>
                    Delete session key
                </a>
            </div>
            <h4>Session key: <span class="label label-success">Active</span></h4>
            <small class="text-muted">Created {{ userkey.session_key.created }}</small>
        {% else %}
            <h4>No active session key</h4>
        {% endif %}
    {% else %}
        <p>You don't have a user key on file.</p>
        <p>
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-primary">
                <span class="fa fa-plus" aria-hidden="true"></span>
                Create a User Key
            </a>
        </p>
    {% endif %}
{% endblock %}

netbox/templates/users/userkey_edit.html
{% extends 'users/_user.html' %}
{% load static %}
{% load form_helpers %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if userkey.is_active %}
        <div class="alert alert-danger" role="alert">
            <strong>Warning:</strong> Changing your public key will require your user key to be re-activated by another
            user. You will be unable to retrieve any secrets until your key has been reactivated.
        </div>
    {% endif %}
    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.public_key %}
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-sm-6 col-md-6">
                    <button type="button" class="btn btn-info" id="generate_keypair">Generate a New Key Pair</button>
                </div>
                <div class="col-sm-6 col-md-6 text-right">
                    <button type="submit" name="_update" class="btn btn-primary">Save</button>
                    <a href="{% url 'user:userkey' %}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="new_keypair_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="new_keypair_modal_title">
                        New RSA Key Pair
                    </h4>
                </div>
                <div class="modal-body">
                    <strong>New Public Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_pubkey" style="height: 250px;"></textarea>
                    </div>
                    <strong>New Private Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_privkey" style="height: 250px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-danger" id="use_new_pubkey" data-dismiss="modal">I have saved my new private key</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}